// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities;

public partial class Product
{
    public Guid ProductId { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public int? Quantity { get; set; }

    public double? Price { get; set; }

    public string Size { get; set; }

    public string Status { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();
}